# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(531, 340)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayoutda = QtWidgets.QHBoxLayout()
        self.horizontalLayoutda.setSpacing(1)
        self.horizontalLayoutda.setObjectName("horizontalLayoutda")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.List = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.List.setFont(font)
        self.List.setMouseTracking(False)
        self.List.setTabletTracking(False)
        self.List.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.List.setInputMethodHints(QtCore.Qt.ImhNone)
        self.List.setWordWrap(False)
        self.List.setSelectionRectVisible(False)
        self.List.setObjectName("List")
        self.verticalLayout.addWidget(self.List)
        self.horizontalLayoutda.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Slider1 = QtWidgets.QSlider(self.centralwidget)
        self.Slider1.setOrientation(QtCore.Qt.Vertical)
        self.Slider1.setObjectName("Slider1")
        self.horizontalLayout.addWidget(self.Slider1)
        self.view2d = QtWidgets.QGraphicsView(self.centralwidget)
        self.view2d.setObjectName("view2d")
        self.horizontalLayout.addWidget(self.view2d)
        self.Slider2 = QtWidgets.QSlider(self.centralwidget)
        self.Slider2.setOrientation(QtCore.Qt.Vertical)
        self.Slider2.setObjectName("Slider2")
        self.horizontalLayout.addWidget(self.Slider2)
        self.view3d = QtWidgets.QGraphicsView(self.centralwidget)
        self.view3d.setObjectName("view3d")
        self.horizontalLayout.addWidget(self.view3d)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayoutda.addLayout(self.verticalLayout_2)
        self.NIImessage = QtWidgets.QTextBrowser(self.centralwidget)
        self.NIImessage.setObjectName("NIImessage")
        self.horizontalLayoutda.addWidget(self.NIImessage)
        self.horizontalLayoutda.setStretch(0, 1)
        self.horizontalLayoutda.setStretch(1, 4)
        self.horizontalLayoutda.setStretch(2, 1)
        self.gridLayout.addLayout(self.horizontalLayoutda, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 18))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("actionopen")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("actionhelp")
        self.menu.addSeparator()
        self.menu.addAction(self.action_open)
        self.menu_2.addAction(self.action_help)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCOPE"))
        self.NIImessage.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))

        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.menu_4.setTitle(_translate("MainWindow", "视图"))
        self.menu_5.setTitle(_translate("MainWindow", "设置"))
        self.menu_6.setTitle(_translate("MainWindow", "窗口"))
        self.menu_3.setTitle(_translate("MainWindow", "编辑"))
        self.action_open.setText(_translate("MainWindow", "打开文件夹"))
        self.action_open.setIconText(_translate("MainWindow", "open"))
        self.action_help.setText(_translate("MainWindow", "说明"))

